AllCops:
  TargetRubyVersion: 2.1

Style/SignalException:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/MethodLength :
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Lint/UnusedMethodArgument:
  Enabled: false
